import { initializeApp } from 'firebase/app'
import { getFirestore, collection, addDoc, getDocs, deleteDoc } from 'firebase/firestore'

const firebaseConfig = {
  apiKey: "AIzaSyCPfZ_wqHALFF4bLS5UfX8tr5jmM1QYK8c",
  authDomain: "encco-925e1.firebaseapp.com",
  projectId: "encco-925e1",
  storageBucket: "encco-925e1.firebasestorage.app",
  messagingSenderId: "15019634613",
  appId: "1:15019634613:web:83a54c4b5b655b050933fc"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const productos = [
  // ── COMBOS ─────────────────────────────────────────────────
  { categoria: 'Combos', subcategoria: 'Lata', nombre: 'COMBO LATA', detalle: '12 Und Solera Bohemia', precio: 8, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Lata', nombre: 'COMBO LATA', detalle: '12 Und Solera Azul', precio: 10, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO CACIQUE', detalle: '1 Cacique, 1 Pepsi 1.5 Lt, 1 bolsa de hielo', precio: 10, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO TERESA', detalle: '1 Santa Teresa, 1 Pepsi 1.5 L, 1 bolsa de hielo', precio: 10, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: "COMBO GORDON'S", detalle: "1 Vodka Gordon's 0.70 Lt, 1 7UP 1.5 Lt, 1 bolsa de hielo", precio: 12, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO TERESA ZUMO', detalle: '1 Santa Teresa, 1 Pepsi 1.5 L, 1 bolsa de hielo, 1 zumo de limón', precio: 12, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO CACIQUE ZUMO', detalle: '1 Cacique, 1 Pepsi 1.5 L, 1 bolsa de hielo, 1 zumo de limón', precio: 14, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO LINAJE', detalle: '1 Santa Teresa Linaje, 1 Pepsi 1.5 L, 1 bolsa de hielo', precio: 15, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO 500', detalle: '1 Cacique 500, 1 Pepsi 1.5 L, 1 bolsa de hielo', precio: 16, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO LINAJE ZUMO', detalle: '1 Santa Teresa Linaje, 1 Pepsi 1.5 L, 1 bolsa de hielo, 1 zumo de limón', precio: 18, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO 500 ZUMO', detalle: '1 Cacique 500, 1 Pepsi 1.5 L, 1 bolsa de hielo, 1 zumo de limón', precio: 19, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO DUO LINAJE', detalle: '2 Santa Teresa Linaje', precio: 24, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO DUO CACIQUE 500', detalle: '2 Cacique 500', precio: 25, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO OLD PARR', detalle: '1 Old Parr 12 años, 2 aguas gasificadas, 1 maní salado, 1 maní japonés, 1 frutos secos', precio: 40, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: "COMBO BUCHANAN'S", detalle: "1 Buchanan's 12 años, 2 aguas gasificadas, 1 maní salado, 1 maní japonés, 1 frutos secos", precio: 42, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO SANGRÍA', detalle: '1 Sangría Caroreña, 1 7UP 1.5 Lt, 1 bolsa de hielo', precio: 9, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO SANGRÓN', detalle: '1 Botella Santa Teresa, 1 Sangría Caroreña, 1 Pepsi 1.5 Lt, 1 7UP 1.5 Lt, 1 bolsa de hielo', precio: 17, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO 5 ESTRELLAS RUMBA RON', detalle: '1 Rumba Ron o 5 Estrellas, 1 Pepsi 1.5 Lt, 1 bolsa de hielo', precio: 7.5, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Licor', nombre: 'COMBO BAJO 0', detalle: '1 Bajo 0, 1 7UP 1.5 Lt, 1 bolsa de hielo', precio: 9, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Snack', nombre: 'COMBO NETFLIX', detalle: '2 cotufas de microondas, 1 Dorito, 1 savoy 130 gr, 1 Pepsi 1.5 litros', precio: 10, disponible: true, esCombo: true },
  { categoria: 'Combos', subcategoria: 'Snack', nombre: 'COMBO SNACKS', detalle: '1 cheestris, 1 Pepito, 1 natuchips, 1 cheetos boliqueso o mega puff, 1 Pepsi 1.5 litros', precio: 10, disponible: true, esCombo: true },

  // ── CERVEZAS ───────────────────────────────────────────────
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Polar negra', detalle: null, precio: 21, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Regional', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Zulia', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Polar light', detalle: null, precio: 21, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Solera azul', detalle: null, precio: 21, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Cajas', nombre: 'Solera verde', detalle: null, precio: 23, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Coronita', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Heineken', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Corona', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Stella', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Budweiser', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Solera azul lata', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Solera verde lata', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Polar light lata', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Polar negra lata', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cervezas', subcategoria: 'Unidad', nombre: 'Zulia lata', detalle: null, precio: 1, disponible: true, esCombo: false },

  // ── SNACKS ─────────────────────────────────────────────────
  { categoria: 'Snacks', subcategoria: null, nombre: 'BUBBALOO', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CARAMELOS SALVAVIDA TUBITO', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUTELLA 950 GR', detalle: null, precio: 16, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUTELLA 750 GR', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUTELLA 350 GR', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUTELLA 140 GR', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'OVOMALTINA 1 KG', detalle: null, precio: 15, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'OVOMALTINA 35 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'OVOMALTINA MAXI 100 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'OVOMALTINA 300 GR', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUCITA TUBITO', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUCITA DOBLE SABOR 200 GR', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SKITTLES', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PISTACHOS', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'STARBURST', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'KINDER BUENO', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'HUBBA BUBBA MAX', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'GUMMY BEAR 12 GR (3 UNID)', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NERDS GUMMY', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CARAMELOS JOLLY (6 UNID)', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'HERSHEYS XL', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'RING POP', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PUSH POP', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CARAMELOS MENTOS', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'M&M', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHICLE HUBBA BUBBA', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'HERSHEYS', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'MARILÚ', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'OREO UNIDAD', detalle: null, precio: 0.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'GALLETA MARÍA', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE SAVOY CON LECHE 70 GR', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE SAVOY CON LECHE 130GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE SAVOY CON LECHE 30GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE CRICRI 123 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE CRICRI 60 GR', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE CRICRI 30 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE RIKITI 130 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE RIKITI 30 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE GALACK 130 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE GALACK 30 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SAVOY DE LIGHT 100 GR', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SAVOY DE LIGHT 27 GR', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'BOLSA TORONTO 125 GR', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE CARRE 100 GR', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATE CARRE 25 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SAVOY ANIVERSARIO 100 GR', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'KITKAT', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'MANÍ JACKS 25 GR', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHIPS AHOY 168 GR', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'FERRERO ROCHER', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATES MILKA 100 GR', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'GALLETAS FESTIVAL', detalle: null, precio: 0.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'MANÍ SALADO', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'MANÍ JAPONÉS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'FRUTO SECO', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'BOTECITO', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PANQUÉ', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'YOGURT GRIEGO YOLO', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'DANDY', detalle: null, precio: 0.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUCITA PREMIUM 280 GR', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NUCITA CRUNCH', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'NATUCHIPS', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'MANÍ JACKS', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'RUFFLES', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'RAQUETY 36 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'RAKETY 18 GR', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'DORITOS FLAMING HOT', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PAPAS JACK', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHEETO FLAMING HOT', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SAMBA', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'COCOSETTE', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'HERSHEYS MINI', detalle: null, precio: 0.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PIRULÍN ESTUCHE', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PIRULÍN LATA 155 GR', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PIRULÍN BITES 200 GR', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PIRULÍN LATA 300 GR', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHUPETA (4 UNID)', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'SUSY', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHEESE TRIS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHEETOS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHICHARRÓN PICANTE', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PEPITO', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TORTILLA PICANTE', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'DE TODITO', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'DORITO', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TOSTITOS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PLÁTANO CHIPS 300 GR', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'YUCA CHIPS 180 GR', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'GOMITAS SALVAVIDA', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHOCOLATES IMPORTADOS', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TRULULÚ', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'FLIPS 220 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'FLIPS 120 GR', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TAKIS 50 GR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'COTUFAS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TRIDENT 3', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'CHICLE FIVE', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TRIDENT 1', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'ICED CUBE', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'AIRHEADS', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'AIRHEADS 15 GR', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'TOSTONES DON JOSÉ 150 GR', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'HALLS', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PRINGLES GRANDES', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Snacks', subcategoria: null, nombre: 'PRINGLES PEQUEÑO', detalle: null, precio: 2, disponible: true, esCombo: false },

  // ── WHISKY ─────────────────────────────────────────────────
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS 12 AÑOS', detalle: null, precio: 34, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS 12 AÑOS 1 L', detalle: null, precio: 40, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS 18 AÑOS', detalle: null, precio: 100, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS MASTER 1 L', detalle: null, precio: 60, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS MASTER 0.75 L', detalle: null, precio: 42, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS TWO SOULS', detalle: null, precio: 50, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS 375 ML', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS PIÑA', detalle: null, precio: 70, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BUCHANANS 1.75 L', detalle: null, precio: 75, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'OLD PAR 12 AÑOS', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'OLD PAR 12 AÑOS 1 L', detalle: null, precio: 36, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'OLD PAR 18 AÑOS', detalle: null, precio: 95, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'OLD PAR SILVER', detalle: null, precio: 24, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'OLDPAR 500 ML GALLINITA', detalle: null, precio: 21, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLACK LABEL 1 L', detalle: null, precio: 45, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLACK LABEL 0.75 L', detalle: null, precio: 32, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLUE LABEL', detalle: null, precio: 300, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLUE LABEL EDICION ESPECIAL', detalle: null, precio: 310, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'RED LABEL 1 L', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ETIQUETA DORADA 0.75 L', detalle: null, precio: 65, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ETIQUETA 18 AÑOS', detalle: null, precio: 110, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ETIQUETA NEGRA 1.75 L', detalle: null, precio: 70, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ETIQUETA ROJA 1.75 L', detalle: null, precio: 44, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'JHONNY WALKER XR 21 AÑOS', detalle: null, precio: 155, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE', detalle: null, precio: 155, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 21 AÑOS AMARILLO', detalle: null, precio: 180, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 21 AÑOS NEGRO', detalle: null, precio: 180, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 25 AÑOS', detalle: null, precio: 300, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 25 AÑOS SMALL BATCH', detalle: null, precio: 390, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 21 EDICIÓN POLO', detalle: null, precio: 180, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'ROYAL SALUTE 21 FASHION COLLECTION', detalle: null, precio: 240, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'RED SEAL', detalle: null, precio: 220, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'MACALLAN 12 QUEST', detalle: null, precio: 80, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'MACALLAN 12 SHERRY', detalle: null, precio: 120, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'MACALLAN 12 TRIPLE CASK', detalle: null, precio: 105, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH PROJECT XX', detalle: null, precio: 60, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH 12 AÑOS', detalle: null, precio: 48, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH 15 AÑOS', detalle: null, precio: 70, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH VAT 03 15 AÑOS', detalle: null, precio: 95, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH VAT 04 18 AÑOS', detalle: null, precio: 125, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH RESERVE CASK', detalle: null, precio: 50, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH SELECT CASK', detalle: null, precio: 47, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GLENFIDDICH VINTAGE CASK', detalle: null, precio: 95, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GRANTS 1 L 12 AÑOS', detalle: null, precio: 25, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'XR 19', detalle: null, precio: 155, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'GRANTS 1 L', detalle: null, precio: 15, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLACK AND WHITE', detalle: null, precio: 17, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'BLACK AND WHITE 1.75 L', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'THE FAMOUS GROUSE', detalle: null, precio: 19, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'DEWARS 1 L', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'DEWARS 18 AÑOS 1 L', detalle: null, precio: 48, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'CHIVAS REGAL 12 AÑOS 1 L', detalle: null, precio: 36, disponible: true, esCombo: false },
  { categoria: 'Whisky', subcategoria: null, nombre: 'JHONNY WALKER DOUBLE BLACK', detalle: null, precio: 50, disponible: true, esCombo: false },

  // ── RON ────────────────────────────────────────────────────
  { categoria: 'Ron', subcategoria: null, nombre: 'CACIQUE', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'CACIQUE 500', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'CACIQUE ANTIGUO', detalle: null, precio: 50, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'CACIQUE LEYENDA 0.75 L', detalle: null, precio: 24, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA LINAJE', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA 1796', detalle: null, precio: 28, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA 1796 CAFÉ', detalle: null, precio: 38, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA 1796 WHISKY', detalle: null, precio: 38, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA 1796 CACAO', detalle: null, precio: 38, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'TERESA BLANCO', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'SANTA TERESA 0.75', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'TERESA 1 L', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'DIPLOMATICO RESERVA EXCLUSIVA', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'CARUPANO 6 AÑOS', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'CARUPANO 12 AÑOS', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'RON BLANCO CANAIMA 0.70 L', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'RON 5 ESTRELLAS', detalle: null, precio: 5.5, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'RON RUMBA RON', detalle: null, precio: 5.5, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'BACARDI', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'RON TEPUY DESTINO', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Ron', subcategoria: null, nombre: 'RON TEPUY MONUMENTO', detalle: null, precio: 28, disponible: true, esCombo: false },

  // ── TEQUILA ────────────────────────────────────────────────
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA JOSE CUERVO 1 L', detalle: null, precio: 26, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'JOSE CUERVO 0.75 L', detalle: null, precio: 17, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA JIMADOR 1 L', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA JIMADOR 0.75 L', detalle: null, precio: 28, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA 1800', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA 1800 AÑEJO', detalle: null, precio: 37, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA ROSE 0.75 L', detalle: null, precio: 34, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA DON JULIO 70', detalle: null, precio: 90, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA DON JULIO 1942', detalle: null, precio: 215, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA DON JULIO REPOSADO', detalle: null, precio: 75, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA DON JULIO AÑEJO', detalle: null, precio: 75, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA DON JULIO SILVER', detalle: null, precio: 65, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA PATRON AÑEJO 1 L', detalle: null, precio: 65, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA PATRON SILVER', detalle: null, precio: 50, disponible: true, esCombo: false },
  { categoria: 'Tequila', subcategoria: null, nombre: 'TEQUILA PATRON REPOSADO', detalle: null, precio: 50, disponible: true, esCombo: false },

  // ── VODKA ──────────────────────────────────────────────────
  { categoria: 'Vodka', subcategoria: null, nombre: 'SMIRNOFF', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: "GORDON'S", detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA SMIRNOFF 1 L', detalle: null, precio: 19, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA SMIRNOFF TAMARINDO', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA BAJO CERO', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA FINLANDIA 1 L', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA ABSOLUT 1 L', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA GREY GOOSE 1 L', detalle: null, precio: 42, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA STANISLAFF 0.75 L', detalle: null, precio: 12, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA BELVEDERE 1 L', detalle: null, precio: 36, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA STOLICHNAYA 1 L', detalle: null, precio: 22, disponible: true, esCombo: false },
  { categoria: 'Vodka', subcategoria: null, nombre: 'VODKA 0.70 L', detalle: null, precio: 16, disponible: true, esCombo: false },

  // ── GINEBRA ────────────────────────────────────────────────
  { categoria: 'Ginebra', subcategoria: null, nombre: 'GORDONS GINEBRA', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Ginebra', subcategoria: null, nombre: 'GINEBRA TANQUERAY 1 L', detalle: null, precio: 28, disponible: true, esCombo: false },
  { categoria: 'Ginebra', subcategoria: null, nombre: 'GINEBRA TANQUERAY 0.70 L', detalle: null, precio: 25, disponible: true, esCombo: false },

  // ── AGUARDIENTE / ANÍS ─────────────────────────────────────
  { categoria: 'Aguardiente / Anís', subcategoria: null, nombre: 'ANIS 1 L', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Aguardiente / Anís', subcategoria: null, nombre: 'ANTIOQUEÑO 260 ML', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Aguardiente / Anís', subcategoria: null, nombre: 'ANTIOQUEÑO 1 L', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Aguardiente / Anís', subcategoria: null, nombre: 'AGUARDIENTE AMARILLO 0.70 L', detalle: null, precio: 16, disponible: true, esCombo: false },

  // ── VINOS, ESPUMANTE Y SANGRÍA ─────────────────────────────
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CHAMPANA FREIXENET', detalle: null, precio: 28, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CHAMPANA BLANCA Y ROSADA', detalle: null, precio: 18, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CHANDON', detalle: null, precio: 26, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'MOET CHANDON ICE', detalle: null, precio: 95, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'MOET CHANDON BRUT', detalle: null, precio: 85, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'MOET CHANDON ROSE', detalle: null, precio: 100, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'PROSECCO MIONETTO 0.75 L', detalle: null, precio: 24, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'PROSECCO SPERONE', detalle: null, precio: 18, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'PROSECCO KIRKLAND', detalle: null, precio: 19, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'PROSECCO CRUZ DEL SUR', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'PROSECCO PICCINI', detalle: null, precio: 27, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'SANGRIA LA QUE MANDA', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'SANGRIA CAROREÑA', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'SANGRIA LATA MOJITO', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'SANGRIA LATA', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO WINKING OWL CABERNET', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO WINKING OWL MERLOT', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO WINKING OWL PINOT GRIGIO', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO WINKING OWL SWEET RED', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO WINKING OWL SAUVIGNON BLANC', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CATENA CABERNET', detalle: null, precio: 23, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CATENA MALBEC', detalle: null, precio: 23, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'FRONTERA CABERNET', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'FRONTERA MERLOT', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'FRONTERA SAUVIGNON BLANC', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CASILLERO DEL DIABLO CABERNET', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CASILLERO DEL DIABLO MERLOT', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CASILLERO DEL DIABLO MALBEC', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'CASILLERO DEL DIABLO SAUVIGNON BLANC', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'TORO MALBEC', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'TORO MERLOT', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO MAIPO', detalle: null, precio: 11, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'VINO MAIPO SAUVIGNON BLANC', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'RESERVADO SAUVIGNON BLANC', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'AGUA SANTA SAUVIGNON BLANC', detalle: null, precio: 11, disponible: true, esCombo: false },
  { categoria: 'Vinos, Espumante y Sangría', subcategoria: null, nombre: 'JP CHENET LATA', detalle: null, precio: 4, disponible: true, esCombo: false },

  // ── OTROS LICORES ──────────────────────────────────────────
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'BAILEYS 1 L', detalle: null, precio: 27, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'MARGARITA KIRKLAND', detalle: null, precio: 24, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'TRIPLE SEC', detalle: null, precio: 26, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'JAGGER 1 L', detalle: null, precio: 32, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'LOS CUATES', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'FOURLOKO', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'NAIGUATA', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'LIMONCELLO 0.70 L', detalle: null, precio: 36, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'FRANGELICO 1 L', detalle: null, precio: 30, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'DISARONNO AMARETTO 1 L', detalle: null, precio: 32, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'SOMETHING SPECIAL', detalle: null, precio: 24, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'JHON BARR ROJO', detalle: null, precio: 15, disponible: true, esCombo: false },
  { categoria: 'Otros Licores', subcategoria: null, nombre: 'JHON BARR NEGRO', detalle: null, precio: 17, disponible: true, esCombo: false },

  // ── BEBIDAS ────────────────────────────────────────────────
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MINALBA 600 ML', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA FIEL 600 ML', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MINALBA GASIFICADA', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MINALBA 1.5L', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA FIEL 1.5 L', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA VALLE VERDE 5 L', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA FIEL 5 L', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA PERRIER', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MINALBA 5L', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'CAJA AGUA CRISTAL', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'CAJA AGUA FIEL 330 ML', detalle: null, precio: 12, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'CAJA AGUA NEVADA 355 ML', detalle: null, precio: 12, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'CAJA AGUA MINALBA 355 ML', detalle: null, precio: 18, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NEVADA SABORIZADAS CON GAS 330 ML', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NEVADA SABORIZADAS CON GAS 1.5 L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA GASIFICADA PERRIER', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MALTA DE LATA', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'GINGER ALE', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'PEPSI 1.5L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: '7UP 1.5L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'SODA EVERVESS LATA', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUAKINA LATA', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'PEPSI 2L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'PEPSI LIGHT 2L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: '7UP 2L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'FRESCOLITA 2 L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'MALTA 1.5 LTS', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: '90 MINUTOS HIDRATANTE', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'POWERADE', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'LIPTON LIMON 500ML', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'ELECTROLIT', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'GATORADE', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'JUGO NATULAC', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'ZUMO LIMON', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'YUKERY DURAZNO 1.5L', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'YUKERY NARANJA 1.5L', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'YUKERY PERA 1.5L', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'YUKERY MANZANA 1.5L', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NESTEA 90 GR', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'TE NATURE 330 ML', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'TE NATULAC', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NESTEA 250 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'LIPTON 1.5L', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'TE NATURE 1.2 L', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NESTEA 450 GR', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'TE NATURE 3.7 L', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'NESTEA 1 KG', detalle: null, precio: 14, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'TORONJA 9 GRADOS', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA DE COCO 250 ML', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'AGUA DE COCO 1 L', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'GRANADINA', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'CRANBERRY', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'APEROL 1 L', detalle: null, precio: 35, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA 1 L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA SIN AZÚCAR 1 L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA 1.5 L', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA 2 L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA SIN AZÚCAR 2 L', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Bebidas', subcategoria: null, nombre: 'COCA COLA DE LATA 355 ML', detalle: null, precio: 1.5, disponible: true, esCombo: false },

  // ── ENERGIZANTES ───────────────────────────────────────────
  { categoria: 'Energizantes', subcategoria: null, nombre: 'REDBULL', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'CELSIUS', detalle: null, precio: 4.5, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'ROCKSTAR', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: '90 MINUTOS', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'SPEEDMAX', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'MONSTER', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'MONSTER SIN AZÚCAR', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Energizantes', subcategoria: null, nombre: 'BLOOM', detalle: null, precio: 4.5, disponible: true, esCombo: false },

  // ── CIGARROS ───────────────────────────────────────────────
  { categoria: 'Cigarros', subcategoria: null, nombre: 'BELMONT G', detalle: null, precio: 3, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'LUCKY STRIKE', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'UNIVERSAL', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'TIME DOUBLE CHANGE', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'BOHEM NORMAL', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'BOHEM DOUBLE CLICK', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'CLIPPER', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Cigarros', subcategoria: null, nombre: 'YESQUERO', detalle: null, precio: 0.5, disponible: true, esCombo: false },

  // ── ARGUILE ────────────────────────────────────────────────
  { categoria: 'Arguile', subcategoria: null, nombre: 'CARBÓN PARA ARGUILE (4 UNID)', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'CARBÓN VEGETAL 1.5 KG', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'CARBÓN VEGETAL 3 KG', detalle: null, precio: 7.5, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'CARBÓN INSTANTÁNEO 1.5 KG', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'ESENCIA ARGUILE 50 GR', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'ESENCIA ALFAKHER', detalle: null, precio: 12, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'ESENCIAS ARGUILE LIMÓN 250 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'ESENCIAS ARGUILE TWO APPLE 250 GR', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Arguile', subcategoria: null, nombre: 'BOQUILLAS DESECHABLES ARGUILE', detalle: null, precio: 1, disponible: true, esCombo: false },

  // ── HELADOS / MARQUESAS ────────────────────────────────────
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Cornetto 115 ml', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Chocolito Max 80 ml', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Cornetto Vasito Jazz 160 ml', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Merengada Vasito 150 ml', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Sandwich 135 ml', detalle: null, precio: 3.5, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Magnum', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Bati Bati', detalle: null, precio: 2, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tío Rico', nombre: 'Sabores / Pirulín / Oreo 700 ml', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Tradicional', nombre: 'Sabores / Fresa / Chocolate / Mantecado 850 ml', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Fantoche', nombre: 'Sabores / Fresa / Chocolate / Mantecado 700 ml', detalle: null, precio: 7.5, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Trisabor 2 L', detalle: null, precio: 15, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Fresa', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Chocolate', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Mantecada', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Pistacha', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Ron Pasas', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Tramontana', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Cookies & Cream', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados La Argentina', nombre: 'Crema Fantasía', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Efe', nombre: 'Tradicional 435 ml', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Efe', nombre: 'Tradicional 920 ml', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Efe', nombre: 'Toddy 920 ml', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Efe', nombre: 'Trisabor 2 L', detalle: null, precio: 17, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Gatelli', nombre: 'Oreo', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Gatelli', nombre: 'Clásico', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Gatelli', nombre: 'Fit', detalle: null, precio: 4, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Gatelli', nombre: 'Clásico Fudge', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Helados Cremosos', nombre: '946 ML', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Marquesart', nombre: 'Sabores nacionales', detalle: null, precio: 6, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Marquesart', nombre: 'Sabores importados', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Marquesart', nombre: 'Sabores combinados', detalle: null, precio: 8, disponible: true, esCombo: false },
  { categoria: 'Helados / Marquesas', subcategoria: 'Marquesart', nombre: 'Sin azúcar', detalle: null, precio: 11, disponible: true, esCombo: false },

  // ── OTROS ──────────────────────────────────────────────────
  { categoria: 'Otros', subcategoria: null, nombre: 'CAVA HOTELERA', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CAVA MEDIANA', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CAVA GRANDE', detalle: null, precio: 15, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CARGADORES 1 METRO', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CARGADORES 2 METROS', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CUBO CARGADOR DOBLE', detalle: null, precio: 13, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CUBO CARGADOR', detalle: null, precio: 9, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'BATERÍA PORTÁTIL', detalle: null, precio: 20, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'RECEPTOR BLUETOOTH', detalle: null, precio: 10, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CARGADOR DE CARRO', detalle: null, precio: 7, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'BATERÍA AA', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'BATERÍA AAA', detalle: null, precio: 2.5, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'LIBID HONEY', detalle: null, precio: 5, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'ULTRA FER', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'CONDONES', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'BOLSA DE HIELO', detalle: null, precio: 1.5, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'VASOS ROJOS', detalle: null, precio: 0.25, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'VASOS DE ALUMINIO', detalle: null, precio: 1, disponible: true, esCombo: false },
  { categoria: 'Otros', subcategoria: null, nombre: 'DOMINO ENCCO', detalle: null, precio: 10, disponible: true, esCombo: false },
]

async function seed() {
  console.log(`Subiendo ${productos.length} productos a Firestore...`)
  const col = collection(db, 'productos')

  // Limpiar existentes
  const existing = await getDocs(col)
  for (const d of existing.docs) await deleteDoc(d.ref)
  console.log('Colección limpiada.')

  let count = 0
  for (const p of productos) {
    await addDoc(col, p)
    count++
    if (count % 50 === 0) console.log(`${count}/${productos.length}...`)
  }
  console.log(`✅ ${count} productos subidos exitosamente.`)
  process.exit(0)
}

seed().catch(e => { console.error(e); process.exit(1) })
